### PR TITLE
Adding a check before send the value for a foreach, avoiding the erro…

### PR DESCRIPTION
**Pull request by reisraff**
Adding a check before send the value for a foreach, avoiding the error: Invalid Argument supplied for foreach.

### CODE REVIEW

**Comment by klaussilveira** [comment]
Please check the CI run: https://travis-ci.org/LinioIT/input/builds/436181735#L600

**Comment by reisraff** [comment]
I did, should I change the PHP version requirement for >= 7.1 or change the type for "array" instead of "iterable"?

**Comment by nesl247** [comment]
You should change it to type array since we are still supporting PHP 7.0 with this library at the moment.

**Comment by reisraff** [comment]
@klaussilveira @nesl247 done

**Pull request merged**
